selenium-hub:
  image: selenium/hub
  container_name: 'selenium-hub'
  ports:
    - 4444:4444

chrome:
  image: selenium/node-chrome-debug
  container_name: 'chrome'
  links:
    - selenium-hub:hub
  ports:
    - 5900:5900
  volumes:
    - /dev/shm:/dev/shm
firefox:
  image: selenium/node-firefox-debug
  container_name: 'firefox'
  ports:
    - 5910:5900
  links:
    - selenium-hub:hub
python3:
  #restart: always
  build: './scraping'
  container_name: 'python3'
  command: 'tail -f /dev/null'
  environment:
    TZ: Asia/Tokyo
  links:
    - selenium-hub:hub
  working_dir: '/app'
  volumes:
    - ./opt:/app